### ISSUE TITLE
Crash when joining multiplayer server 

### ISSUE THREAD

**Issue by Akinesis** [Alminoris/ArborealNature#4]
I'm playing on a rather big modpack.

The game and the server launch without a problem but uppon connecting to the server my game crash with the folowing logd :

```
[20:04:57] [Render thread/INFO]: Initializing bushierflowers Mixins
[20:05:13] [Render thread/INFO]: Connecting to 111.222.333.444, 26960
[20:05:13] [Netty Client IO #1/INFO]: Versions match 4.0.0-beta20
[20:05:13] [Netty Client IO #1/INFO]: Http url from connected server: http://111.222.333.444:26960
[20:05:13] [Netty Client IO #1/INFO]: Checking files...
[20:05:17] [Netty Client IO #1/INFO]: automodpack\modpacks\The Fox Den Modpack is up to date!
[20:05:18] [Render thread/ERROR]: Registry remapping failed!
java.util.concurrent.CompletionException: java.lang.RuntimeException: Errors while remapping Int2ObjectMap ItemModels.modelIds found:
 - Map contained two equal IDs 2811 (arborealnature:pine_hanging_sign/2808 -> arborealnature:pine_hanging_sign/2811)!
 - Map contained two equal IDs 2769 (arborealnature:plum_hanging_sign/2769 -> arborealnature:plum_hanging_sign/2769)!
 - Map contained two equal IDs 2780 (arborealnature:fig_sign/2776 -> arborealnature:fig_sign/2780)!
 - Map contained two equal IDs 2762 (arborealnature:quince_sign/2762 -> arborealnature:quince_sign/2762)!
 - Map contained two equal IDs 18370 (wildfields:tamarisk_sign/18370 -> wildfields:tamarisk_sign/18370)!
 - Map contained two equal IDs 2489 (arborealnature:blueberry/2489 -> arborealnature:blueberry/2489)!
 - Map contained two equal IDs 2799 (arborealnature:white_mulberry_hanging_sign/2799 -> arborealnature:white_mulberry_hanging_sign/2799)!
 - Map contained two equal IDs 2751 (arborealnature:hornbeam_hanging_sign/2751 -> arborealnature:hornbeam_hanging_sign/2751)!
 - Map contained two equal IDs 2744 (arborealnature:hazelnut_sign/2740 -> arborealnature:hazelnut_sign/2744)!
 - Map contained two equal IDs 2775 (arborealnature:mango_hanging_sign/2772 -> arborealnature:mango_hanging_sign/2775)!
 - Map contained two equal IDs 2745 (arborealnature:hazelnut_hanging_sign/2745 -> arborealnature:hazelnut_hanging_sign/2745)!
 - Map contained two equal IDs 2805 (arborealnature:bauhinia_hanging_sign/2805 -> arborealnature:bauhinia_hanging_sign/2805)!
 - Map contained two equal IDs 2481 (arborealnature:orchid_lily_pad/2479 -> arborealnature:orchid_lily_pad/2481)!
 - Map contained two equal IDs 2804 (arborealnature:bauhinia_sign/2800 -> arborealnature:bauhinia_sign/2804)!
 - Map contained two equal IDs 2793 (arborealnature:wild_cherry_hanging_sign/2793 -> arborealnature:wild_cherry_hanging_sign/2793)!
 - Map contained two equal IDs 2756 (arborealnature:hawthorn_sign/2756 -> arborealnature:hawthorn_sign/2756)!
 - Map contained two equal IDs 2485 (arborealnature:blackberry/2484 -> arborealnature:blackberry/2485)!
 - Map contained two equal IDs 2798 (arborealnature:white_mulberry_sign/2798 -> arborealnature:white_mulberry_sign/2798)!
 - Map contained two equal IDs 18364 (wildfields:olive_sign/18364 -> wildfields:olive_sign/18364)!
 - Map contained two equal IDs 2787 (arborealnature:viburnum_hanging_sign/2784 -> arborealnature:viburnum_hanging_sign/2787)!
 - Map contained two equal IDs 18365 (wildfields:olive_hanging_sign/18365 -> wildfields:olive_hanging_sign/18365)!
 - Map contained two equal IDs 2774 (arborealnature:mango_sign/2774 -> arborealnature:mango_sign/2774)!
 - Map contained two equal IDs 2786 (arborealnature:viburnum_sign/2782 -> arborealnature:viburnum_sign/2786)!
 - Map contained two equal IDs 18371 (wildfields:tamarisk_hanging_sign/18368 -> wildfields:tamarisk_hanging_sign/18371)!
 - Map contained two equal IDs 2763 (arborealnature:quince_hanging_sign/2760 -> arborealnature:quince_hanging_sign/2763)!
 - Map contained two equal IDs 2757 (arborealnature:hawthorn_hanging_sign/2757 -> arborealnature:hawthorn_hanging_sign/2757)!
 - Map contained two equal IDs 2483 (arborealnature:bilberry/2483 -> arborealnature:bilberry/2483)!
 - Map contained two equal IDs 2487 (arborealnature:pink_currant/2487 -> arborealnature:pink_currant/2487)!
 - Map contained two equal IDs 2768 (arborealnature:plum_sign/2764 -> arborealnature:plum_sign/2768)!
 - Map contained two equal IDs 2750 (arborealnature:hornbeam_sign/2750 -> arborealnature:hornbeam_sign/2750)!
 - Map contained two equal IDs 2810 (arborealnature:pine_sign/2806 -> arborealnature:pine_sign/2810)!
 - Map contained two equal IDs 2792 (arborealnature:wild_cherry_sign/2792 -> arborealnature:wild_cherry_sign/2792)!
 - Map contained two equal IDs 2781 (arborealnature:fig_hanging_sign/2778 -> arborealnature:fig_hanging_sign/2781)!
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.RuntimeException: Errors while remapping Int2ObjectMap ItemModels.modelIds found:
 - Map contained two equal IDs 2811 (arborealnature:pine_hanging_sign/2808 -> arborealnature:pine_hanging_sign/2811)!
 - Map contained two equal IDs 2769 (arborealnature:plum_hanging_sign/2769 -> arborealnature:plum_hanging_sign/2769)!
 - Map contained two equal IDs 2780 (arborealnature:fig_sign/2776 -> arborealnature:fig_sign/2780)!
 - Map contained two equal IDs 2762 (arborealnature:quince_sign/2762 -> arborealnature:quince_sign/2762)!
 - Map contained two equal IDs 18370 (wildfields:tamarisk_sign/18370 -> wildfields:tamarisk_sign/18370)!
 - Map contained two equal IDs 2489 (arborealnature:blueberry/2489 -> arborealnature:blueberry/2489)!
 - Map contained two equal IDs 2799 (arborealnature:white_mulberry_hanging_sign/2799 -> arborealnature:white_mulberry_hanging_sign/2799)!
 - Map contained two equal IDs 2751 (arborealnature:hornbeam_hanging_sign/2751 -> arborealnature:hornbeam_hanging_sign/2751)!
 - Map contained two equal IDs 2744 (arborealnature:hazelnut_sign/2740 -> arborealnature:hazelnut_sign/2744)!
 - Map contained two equal IDs 2775 (arborealnature:mango_hanging_sign/2772 -> arborealnature:mango_hanging_sign/2775)!
 - Map contained two equal IDs 2745 (arborealnature:hazelnut_hanging_sign/2745 -> arborealnature:hazelnut_hanging_sign/2745)!
 - Map contained two equal IDs 2805 (arborealnature:bauhinia_hanging_sign/2805 -> arborealnature:bauhinia_hanging_sign/2805)!
 - Map contained two equal IDs 2481 (arborealnature:orchid_lily_pad/2479 -> arborealnature:orchid_lily_pad/2481)!
 - Map contained two equal IDs 2804 (arborealnature:bauhinia_sign/2800 -> arborealnature:bauhinia_sign/2804)!
 - Map contained two equal IDs 2793 (arborealnature:wild_cherry_hanging_sign/2793 -> arborealnature:wild_cherry_hanging_sign/2793)!
 - Map contained two equal IDs 2756 (arborealnature:hawthorn_sign/2756 -> arborealnature:hawthorn_sign/2756)!
 - Map contained two equal IDs 2485 (arborealnature:blackberry/2484 -> arborealnature:blackberry/2485)!
 - Map contained two equal IDs 2798 (arborealnature:white_mulberry_sign/2798 -> arborealnature:white_mulberry_sign/2798)!
 - Map contained two equal IDs 18364 (wildfields:olive_sign/18364 -> wildfields:olive_sign/18364)!
 - Map contained two equal IDs 2787 (arborealnature:viburnum_hanging_sign/2784 -> arborealnature:viburnum_hanging_sign/2787)!
 - Map contained two equal IDs 18365 (wildfields:olive_hanging_sign/18365 -> wildfields:olive_hanging_sign/18365)!
 - Map contained two equal IDs 2774 (arborealnature:mango_sign/2774 -> arborealnature:mango_sign/2774)!
 - Map contained two equal IDs 2786 (arborealnature:viburnum_sign/2782 -> arborealnature:viburnum_sign/2786)!
 - Map contained two equal IDs 18371 (wildfields:tamarisk_hanging_sign/18368 -> wildfields:tamarisk_hanging_sign/18371)!
 - Map contained two equal IDs 2763 (arborealnature:quince_hanging_sign/2760 -> arborealnature:quince_hanging_sign/2763)!
 - Map contained two equal IDs 2757 (arborealnature:hawthorn_hanging_sign/2757 -> arborealnature:hawthorn_hanging_sign/2757)!
 - Map contained two equal IDs 2483 (arborealnature:bilberry/2483 -> arborealnature:bilberry/2483)!
 - Map contained two equal IDs 2487 (arborealnature:pink_currant/2487 -> arborealnature:pink_currant/2487)!
 - Map contained two equal IDs 2768 (arborealnature:plum_sign/2764 -> arborealnature:plum_sign/2768)!
 - Map contained two equal IDs 2750 (arborealnature:hornbeam_sign/2750 -> arborealnature:hornbeam_sign/2750)!
 - Map contained two equal IDs 2810 (arborealnature:pine_sign/2806 -> arborealnature:pine_sign/2810)!
 - Map contained two equal IDs 2792 (arborealnature:wild_cherry_sign/2792 -> arborealnature:wild_cherry_sign/2792)!
 - Map contained two equal IDs 2781 (arborealnature:fig_hanging_sign/2778 -> arborealnature:fig_hanging_sign/2781)!
	at knot/net.fabricmc.fabric.impl.registry.sync.trackers.Int2ObjectMapTracker.onRemap(Int2ObjectMapTracker.java:89) ~[fabric-registry-sync-v0-5.2.0+34f5d91419-3824caea68cf4e3e.jar:?]
	at knot/net.minecraft.class_2370.md9ac40d$fabric-registry-sync-v0$lambda$init$2$1(class_2370.java:1140) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2370.remap(class_2370.java:1352) ~[client-intermediary.jar:?]
	at knot/net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:280) ~[fabric-registry-sync-v0-5.2.0+34f5d91419-3824caea68cf4e3e.jar:?]
	at knot/net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:141) ~[fabric-registry-sync-v0-5.2.0+34f5d91419-3824caea68cf4e3e.jar:?]
	... 11 more
[20:05:18] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Ticking screen
	at knot/net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1574(class_310.java:1930) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.NullPointerException
	at knot/com.google.common.collect.Iterators$6.transform(Iterators.java:829) ~[guava-32.1.2-jre.jar:?]
	at knot/com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-32.1.2-jre.jar:?]
	at knot/net.minecraft.class_2370.remap(class_2370.java:1247) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2370.unmap(class_2370.java:1378) ~[client-intermediary.jar:?]
	at knot/net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.unmap(RegistrySyncManager.java:367) ~[fabric-registry-sync-v0-5.2.0+34f5d91419-3824caea68cf4e3e.jar:?]
	at knot/net.minecraft.class_310.handler$blo000$fabric-registry-sync-v0$disconnectAfter(class_310.java:9691) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_18096(class_310.java:2269) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8673.method_10839(class_8673.java:319) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8674.method_10839(class_8674.java:148) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2535.method_10768(class_2535.java:673) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_412.method_25393(class_412.java:175) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1572(class_310.java:1930) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 7 more
```

The crash report : https://pastebin.com/Tp0RMuU2

Do note that the server and client wotk just fine when your mod is not instaled.
The game don't crash on single player.
Thank you for your work.

**Comment by Alminoris** [comment]
The issue was fixed with update 0.3.1.2 for Arboreal Nature and 1.0.1 for Wild Fields

**Comment by Akinesis** [comment]
Hello, i still have a problem of similar nature on multiplayer :

```
[00:24:52] [Render thread/ERROR]: Registry remapping failed!
java.util.concurrent.CompletionException: java.lang.RuntimeException: Errors while remapping Int2ObjectMap ItemModels.modelIds found:
 - Map contained two equal IDs 2481 (arborealnature:orchid_lily_pad/2479 -> arborealnature:orchid_lily_pad/2481)!
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.RuntimeException: Errors while remapping Int2ObjectMap ItemModels.modelIds found:
 - Map contained two equal IDs 2481 (arborealnature:orchid_lily_pad/2479 -> arborealnature:orchid_lily_pad/2481)!
	at knot/net.fabricmc.fabric.impl.registry.sync.trackers.Int2ObjectMapTracker.onRemap(Int2ObjectMapTracker.java:89) ~[fabric-registry-sync-v0-5.2.0+34f5d91419-3824caea68cf4e3e.jar:?]
	at knot/net.minecraft.class_2370.md54d92f$fabric-registry-sync-v0$lambda$init$2$1(class_2370.java:1140) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2370.remap(class_2370.java:1352) ~[client-intermediary.jar:?]
	at knot/net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:280) ~[fabric-registry-sync-v0-5.2.0+34f5d91419-3824caea68cf4e3e.jar:?]
	at knot/net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:141) ~[fabric-registry-sync-v0-5.2.0+34f5d91419-3824caea68cf4e3e.jar:?]
	... 11 more
[00:24:53] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Ticking screen
	at knot/net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1574(class_310.java:1930) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.NullPointerException
	at knot/com.google.common.collect.Iterators$6.transform(Iterators.java:829) ~[guava-32.1.2-jre.jar:?]
	at knot/com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52) ~[guava-32.1.2-jre.jar:?]
	at knot/net.minecraft.class_2370.remap(class_2370.java:1247) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2370.unmap(class_2370.java:1378) ~[client-intermediary.jar:?]
	at knot/net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.unmap(RegistrySyncManager.java:367) ~[fabric-registry-sync-v0-5.2.0+34f5d91419-3824caea68cf4e3e.jar:?]
	at knot/net.minecraft.class_310.handler$blo000$fabric-registry-sync-v0$disconnectAfter(class_310.java:9691) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_18096(class_310.java:2269) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8673.method_10839(class_8673.java:319) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8674.method_10839(class_8674.java:148) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2535.method_10768(class_2535.java:673) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_412.method_25393(class_412.java:175) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1572(class_310.java:1930) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 7 more
```

**Comment by Alminoris** [comment]
I understood, its the same but for another block. I've fixed it for signs and berry bushes but not for orchid lily pad. Sorry, It was my inattention)

**Comment by Alminoris** [comment]
I've already re-uploaded the file for 0.3.1.2 version

**Comment by Akinesis** [comment]
I've just tested and it's working (with Wild Fields also instaled on the server.
Thank you for your great work.
